version: "3.7"

services:
  database:
    build: database
    ports:
    - 5432:5432

  frontend:
    build: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - 8080:8080
    command: ['python', 'main.py']